### ISSUE TITLE
Finish converting to .net core

### ISSUE THREAD

**Issue by matthewreily** [jammerware/margiebot#18]
I noticed that there is partial implementation of converting the existing project to .net core.  Would like to see this finished and am willing to help out.

**Comment by jammerware** [comment]
Thanks! I appreciate the offer. I'm actually in the middle of a big move,
but I'm looking forward to finishing the port - it'll likely happen
sometime this week and be pushed to github. Will update this issue.

**Comment by jammerware** [comment]
Converted to core. Still some outstanding issues that seem to occur when using in classic .NET. Looking into it, but the port is done.
