### ISSUE TITLE
CodeWake page is not working

### ISSUE THREAD

**Issue by pacifical** [jammerware/margiebot#27]
Application error 
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

<img width="1440" alt="2018-01-17 23 25 16" src="https://user-images.githubusercontent.com/14069677/35065240-bb583418-fbdd-11e7-99ee-0a6f01d66f29.png">

**Comment by jammerware** [comment]
Looks like Codewake is no longer a thing. I pulled the reference. thanks!
