### ISSUE TITLE
MargieBot 2.0.0 to support .net 4.5.2?

### ISSUE THREAD

**Issue by fuzzbuzzz** [jammerware/margiebot#8]
hi, 

sorry, this is a question rather than an issue. 
Are you planning that MargieBot 2.0.0 supports .net 4.5.2? 

thanks, 
Steven.

**Comment by ghost** [comment]
Well, I just cloned the repo and have been using Visual Studio 2015 and
.NET 4.6 since I started working on it, with only minimal library updates
necessary.

**Comment by jammerware** [comment]
Yup, that was going to be my recommendation. As far as I know, MargieBot as she stands in the master branch today should in 4.5.2 with minimal effort. Just retarget and you should be (relatively) good to go.

As anyone using MargieBot can probably tell, I'm quite new to open source and to library project management in general, so versioning hasn't been strong from me so far :) My plan - when I get some time - is to actually rebuild her on .NET vNext. This'll let her exist in solutions as old as "classic" 4.5.1 and as bleeding edge as Universal Windows Platform. I've done similar things already to my general toolbox library [Bazam](https://github.com/jammerware/bazam), so with any luck that'll be helpful to some people. I've already started, and it'll be a little tricky, but I think I can get there.

If anyone has any thoughts on that, feel free to share. Thank you all for helping me make the framework better!
